spec:
  system: "oscar-example"
  type: website
  lifecycle: experimental
  owner: ""
metadata:
  name: "nodejs-sample"
  annotations:
    github.com/project-slug: "bcgov/nr-nodejs-sample"
    playbook.io.nrs.gov.bc.ca/useAltAppDirName: false
    playbook.io.nrs.gov.bc.ca/addWebadeConfig: true
    playbook.io.nrs.gov.bc.ca/clientId: e985d455-b0ff-470b-8731-e004fcfac915
    license: Apache-2.0
    playbook.io.nrs.gov.bc.ca/publishArtifactSuffix: dist node_modules package.json package-lock.json
    composer.io.nrs.gov.bc.ca/generators: gh-nodejs-build,backstage,nr-repository-composer,gh-oci-deploy-onprem
    playbook.io.nrs.gov.bc.ca/unitTestsPath: ./.github/workflows/test.yaml
    playbook.io.nrs.gov.bc.ca/postDeployTestsPath: ""
    playbook.io.nrs.gov.bc.ca/deploymentConfigPaths: playbooks
    playbook.io.nrs.gov.bc.ca/nodeVersion: "24"
    playbook.io.nrs.gov.bc.ca/nodePattern: NPM
    playbook.io.nrs.gov.bc.ca/ociArtifacts: ""
    playbook.io.nrs.gov.bc.ca/artifactRepositoryType: GitHubPackages
    playbook.io.nrs.gov.bc.ca/artifactRepositoryPath: https://maven.pkg.github.com/bcgov/nr-nodejs-sample
    playbook.io.nrs.gov.bc.ca/toolsBuildSecrets: ""
    playbook.io.nrs.gov.bc.ca/toolsLocalBuildSecrets: ""
    playbook.io.nrs.gov.bc.ca/deployType: nodejs
  description: NodeJS sample application
  title: NodeJS Sample
apiVersion: backstage.io/v1alpha1
kind: Component
